apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: kf-004
  region: eu-west-2
  version: "1.18"
nodeGroups:
- desiredCapacity: 2
  instanceType: m5.xlarge
  maxSize: 3
  minSize: 0
  name: cpu-nodegroup
  volumeSize: 30
