output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value = module.eks.config_map_aws_auth
}


output "cluster_name" {
  description = "Kubernetes Cluster Name."
  value = var.cluster_name
}

output "cluster_role_name" {
  description = "Name of the role that kubeflow will use to control the cluster."
  value = aws_iam_role.node_instance_role.name
}

output "cluster_autoscale_role_name" {
  description = "Name of the role that EKS uses to autoscale"
  value = local.cluster_autoscale_role_name
}

output "aws_account_id" {
  value = data.aws_caller_identity.current.account_id
}